version: '3.4'

services:
  conferenceattendees.api:
    image: ${DOCKER_REGISTRY-}conferenceattendeesapi
    build:
      context: .
      dockerfile: ConferenceAttendees.API/Dockerfile
    ports:
      - "7106:7106"
    environment:
      - ASPNETCORE_URLS=http://*:7106
    depends_on:
      - mssql
    networks:
      - app-network
  conferenceattendees.mvc:
    image: ${DOCKER_REGISTRY-}conferenceattendeesmvc
    build:
      context: .
      dockerfile: ConferenceAttendees.MVC/Dockerfile
    ports:
      - "7230:7230"
    environment:
      - ASPNETCORE_URLS=http://*:7230
    depends_on:
      - conferenceattendees.api
    networks:
      - app-network
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sql-DockerCompose
    hostname: mssql
    environment: 
      - SA_PASSWORD=P@ssw0rd1
      - ACCEPT_EULA=Y
    restart: unless-stopped
    ports:
      - "1401:1433"
    networks:
      - app-network
  nginx:
    build:
      context: . 
      dockerfile: nginx/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - conferenceattendees.mvc
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
