---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: conferenceattendeesapi
    namespace: cloud-native-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: conferenceattendeesapi
    spec:
      containers:
      - name: conferenceattendeesapi
        image: wickerknox89/conferenceattendees-api:latest
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__ConferenceAttendeeDatabaseConnection
          value: Server=mssql-svc,1434;Database=ConferenceAttendeeDb;Trusted_Connection=false;MultipleActiveResultSets=true;Encrypt=false;user id=sa;password=P@ssw0rd1;
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: conferenceattendeesapi
---
apiVersion: v1
kind: Service
metadata:
  name: conferenceattendeesapi-svc
  namespace: cloud-native-dev
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32001
  selector:
    app: conferenceattendeesapi
